### ISSUE TITLE
Who's doing which state? [tracking issue]

### ISSUE THREAD

**Issue by jeremybmerrill** [openstates/text-extraction#7]
Here's a tracking list of which states are CLAIMED. Please comment below with your claim AND check the box. Check the box when you start (or when you decide you want to do the state), rather than when you're done. We want to avoid two people working on the state in parallel, duplicating work.
- [x] Alabama - AL
- [x] Alaska - AK
- [x] Arizona - AZ
- [x] Arkansas - AR
- [x] California - CA
- [x] Colorado - CO
- [x] Connecticut - CT
- [x] Delaware - DE
- [x] Florida - FL
- [ ] Georgia - GA
- [x] Hawaii - HI
- [x] Idaho - ID
- [x] Illinois - IL
- [ ] Indiana - IN
- [ ] Iowa - IA
- [ ] Kansas - KS
- [ ] Kentucky - KY
- [ ] Louisiana - LA
- [ ] Maine - ME
- [ ] Maryland - MD
- [ ] Massachusetts - MA
- [ ] Michigan - MI
- [ ] Minnesota - MN
- [ ] Mississippi - MS
- [ ] Missouri - MO
- [ ] Montana - MT
- [ ] Nebraska - NE
- [ ] Nevada - NV
- [ ] New Hampshire - NH
- [ ] New Jersey - NJ
- [ ] New Mexico - NM
- [ ] New York - NY
- [ ] North Carolina - NC
- [ ] North Dakota - ND
- [ ] Ohio - OH
- [ ] Oklahoma - OK
- [ ] Oregon - OR
- [ ] Pennsylvania - PA
- [ ] Rhode Island - RI
- [ ] South Carolina - SC
- [ ] South Dakota - SD
- [ ] Tennessee - TN
- [ ] Texas - TX
- [ ] Utah - UT
- [ ] Vermont - VT
- [ ] Virginia - VA
- [ ] Washington - WA
- [ ] West Virginia - WV
- [x] Wisconsin - WI
- [x] Wyoming - WY

**Comment by jeremybmerrill** [comment]
Jeremy and John have done FL, CA and DE. We'll PR them shortly. 

Jeremy is going to do HI.

**Comment by jamesturk** [comment]
closing this, lots of progress this week including some changes to the harness

going to open issues for the remaining states w/ detailed reasons why they're currently blocked to track each individually
